# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

import_from_git(
  url: 'https://github.com/aliaslab-1984/fastlane-utils.git',
  path: 'fastlane/Fastfile-iOS'
)

platform :ios do

  sdk_project_directory = "CoordinatorKit"

  desc "Bootstraps SDK dependencies"
  lane :sdk_bootstrap do
    bootstrap(project_directory: "../" + sdk_project_directory)
  end

  desc "Runs SDK tests"
  lane :sdk_test do
    test(project_directory: sdk_project_directory, scheme: "CoordinatorKit", coverage_target: "CoordinatorKit.framework")
  end

  desc "Runs SwiftLint for the SDK project"
  lane :sdk_lint do
    lint(project_directory: sdk_project_directory)
  end
end
